/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ButtonPanel.java
 * by Ifnu B
 * Created on Apr 29, 2009, 10:27:08 AM
 */
package mfauz.desktop.panel.toolbar;

import javax.swing.JButton;

/**
 *
 * @author kurusgw
 */
public class MasterToolbarPanel extends javax.swing.JPanel {

    /** Creates new form ButtonPanel */
    public MasterToolbarPanel() {
        initComponents();
        kondisiAwal();
    }

    public void kondisiAwal() {
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);

    }

    public void kondisiTambah() {
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
    }

    public void kondisiTabelTerpilih() {
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnKeluar() {
        return btnKeluar;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/tambah.png"))); // NOI18N
        btnTambah.setText("Tambah  ");
        btnTambah.setToolTipText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Edit Data");

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/remove.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setToolTipText("Hapus Data");

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setToolTipText("Simpan Data");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/stop.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setToolTipText("Batal ");

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setToolTipText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSimpanActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    // End of variables declaration//GEN-END:variables
}
