/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginDialog.java
 *
 * Created on May 10, 2009, 10:43:40 PM
 */

package mfauz.desktop.panel.lookup;

import com.artitraining.mfauz.model.Person;
import com.twmacinta.util.MD5;
import mfauz.desktop.util.TextComponentUtils;
import javax.swing.JOptionPane;
import mfauz.desktop.Main;
import mfauz.desktop.frame.MainFrame;

/**
 *
 * @author ifnu
 */
public class LoginDialog1 extends javax.swing.JDialog {

    private Person person;

    /** Creates new form LoginDialog */
    public LoginDialog1() {
        super(MainFrame.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);
        TextComponentUtils.setAutoUpperCaseText(txtPengguna);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPengguna = new javax.swing.JTextField();
        txtKataSandi = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");

        jLabel1.setText("Nama Pengguna");

        jLabel2.setText("Kata Sandi");

        txtKataSandi.setEchoChar('*');
        txtKataSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKataSandiActionPerformed(evt);
            }
        });
        txtKataSandi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKataSandiKeyTyped(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPengguna, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtKataSandi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnKeluar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        //cek user dan password
        if(validateForm()){
        Person p = Main.getAppService().findPersonByNama(txtPengguna.getText());
            String kataSandi = new MD5(new String(txtKataSandi.getPassword())).asHex();
            if(p!=null && p.getPassword().equals(kataSandi)){
                person = p;
                dispose();
            } else {
                JOptionPane.showMessageDialog(MainFrame.getInstance(), "Nama atau Kata Sandi tidak cocok!");
            }
        } 

}//GEN-LAST:event_btnLoginActionPerformed

    public boolean validateForm(){
        if(txtPengguna.getText().length()==0){
            JOptionPane.showMessageDialog(MainFrame.getInstance(), "Nama tidak boleh kosong!");
            return false;
        } else if(txtKataSandi.getPassword() == null || txtKataSandi.getPassword().length==0){
            JOptionPane.showMessageDialog(MainFrame.getInstance(), "Kata Sandi tidak boleh kosong!");
            return false;
        }
        return true;
    }

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtKataSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataSandiActionPerformed
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_txtKataSandiActionPerformed

//tambahan    
    private void txtKataSandiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKataSandiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKataSandiKeyTyped

    public Person showDialog(){
        setVisible(true);
        return person;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtKataSandi;
    private javax.swing.JTextField txtPengguna;
    // End of variables declaration//GEN-END:variables

}
