
/*
 *
 *
 * Created on May 24, 2012, 11:35:25 AM
 */
package mfauz.desktop.panel.lookup;


import com.artitraining.mfauz.model.JenisMutasi;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.util.BigDecimalTableRenderer;
import mfauz.desktop.util.FormUtil;
import mfauz.desktop.util.TextComponentUtils;


/**
 *
 * @author ASUS
 */
public class LookUpJenisMutasi extends javax.swing.JDialog
    implements ListSelectionListener{

    private JenisMutasi jenisMutasi;
    private List<JenisMutasi> listJenisMutasi;
//    private String periode;
//    private BigDecimal TerimaRp;
//    private BigDecimal KeluarRp;
     
    /** Creates new form LookUpBarang */
    public LookUpJenisMutasi(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        listJenisMutasi = Main.getAppService().findAllJenisMutasi();
        tblJenisMutasi.setModel(new JenisMutasiTableModel(listJenisMutasi));
        tblJenisMutasi.setAutoCreateColumnsFromModel(true);
        FormUtil.centerWindow(this);   
        TextComponentUtils.setAutoUpperCaseText(30, txtNama);
    }
    
    public JenisMutasi getJenisMutasi() {
        setVisible(true);
        return jenisMutasi;
    } 
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJenisMutasi = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 450));
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(590, 500));

        tblJenisMutasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE MUTASI", "JENIS MUTASI", "PERIODE", "SALDO TERIMA RP", "SALDO KELUAR RP"
            }
        ));
        tblJenisMutasi.setToolTipText("Sorot PELANGGAN yg Dipilih dan Klik OK!!");
        tblJenisMutasi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblJenisMutasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJenisMutasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJenisMutasi);

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/cekmark_1.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/barang.png"))); // NOI18N
        jLabel2.setText("NAMA MUTASI");

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cari dgn");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel2))
                        .addGap(53, 349, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnOK)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnBatalActionPerformed

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try{
        jenisMutasi = listJenisMutasi.get(tblJenisMutasi.getSelectedRow());
        this.setVisible(false);  
        } catch(Exception ex) {
 
        }  
}//GEN-LAST:event_btnOKActionPerformed

private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
// TODO add your handling code here:
    listJenisMutasi=null;
    listJenisMutasi = Main.getAppService().findJenisMutasi(txtNama.getText());
    tblJenisMutasi.setModel(new JenisMutasiTableModel(listJenisMutasi));
    
    if(listJenisMutasi==null || listJenisMutasi.isEmpty()){
        JOptionPane.showMessageDialog(this, "Pelanggan Tidak Ada!! Perbaiki Pencarian!",
            "Peringatan", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_txtNamaKeyReleased

private void tblJenisMutasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJenisMutasiMouseClicked
}//GEN-LAST:event_tblJenisMutasiMouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
}//GEN-LAST:event_jButton1ActionPerformed

public class JenisMutasiTableModel extends AbstractTableModel{
    private final List<JenisMutasi> listJenisMutasis;
    private final String[] HEADER = new String[] {"KODE", "JENIS MUTASI", "PERIODE" ,"SALDO TERIMA","SALDO KELUAR"};
   
    public JenisMutasiTableModel(List<JenisMutasi> listPelanggan) {
        this.listJenisMutasis = listPelanggan;
    }
    
    
    @Override
    public int getRowCount() {
        return listJenisMutasis.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      JenisMutasi jm= listJenisMutasis.get(rowIndex);
      switch(columnIndex){
          
          case 0:
              return jm.getId();
          case 1:
              return jm.getNamaMutasi();
          case 2:
              return jm.getPeriode();
          case 3:
              return jm.getTerimaRp();
          case 4:
              return jm.getKeluarRp();              
          default:
              return "";
      }
    }
    
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        if(columnIndex==0){return int.class;}
        if(columnIndex==3 || columnIndex==4){return BigDecimal.class;}
            else {
         return String.class;}
        
    }
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if(e.getValueIsAdjusting()) {
        }
    }   
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJenisMutasi;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

   
}
