
/*
 * PanelPembelian.java
 *
 * Created on Jul 7, 2012, 2:19:36 PM
 */
package mfauz.desktop.panel.transaksi;

import com.artitraining.mfauz.model.JenisMutasi;
import com.artitraining.mfauz.model.Mutasi;
import com.artitraining.mfauz.model.Nota;
import com.artitraining.mfauz.model.Person;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.panel.lookup.LookUpJenisMutasi;
import mfauz.desktop.panel.lookup.LookUpPerson;
//import mfauz.desktop.util.NomorNota;
import org.apache.log4j.Logger;
import org.joda.time.DateTime;
import org.openide.util.Exceptions;

public class PanelReceipt extends javax.swing.JComponent {
    public static final String PANEL_NAME = "PENERIMAAN";
    private static PanelReceipt panelReceipt;
//    private List<Mutasi> listMutasi=new ArrayList<Mutasi>();
    private List<Person> listPerson=new ArrayList<Person>();    
    private Mutasi mutasi;
    private Person person;
    private JenisMutasi jenisMutasi;
    private String notajadi, period;
    private Nota nota;
//    private NomorNota nomorNota;
//    private BigDecimal nilaiTerimaRp;
    private static final Logger log = Logger.getLogger(PanelReceipt.class);

    /** Creates new form PanelPembelian */
    public PanelReceipt() {
        initComponents();
        tblReceipt.setAutoCreateColumnsFromModel(false);
        defaultButton();
        enableForm(false);
        txtTanggal.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
//        editButton();
    }
    
     public static PanelReceipt getPanelReceipt() {
        if (panelReceipt == null) {
            panelReceipt = new PanelReceipt();
        }
        return panelReceipt;
    }
    
    private void refreshTable() {
          tblReceipt.setModel(new TabelModelReceipt(listPerson));
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTanggal = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCariPerson = new javax.swing.JButton();
        txtJenisMutasi = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCariJenisMutasi = new javax.swing.JButton();
        txtKeterangan = new javax.swing.JTextField();
        txtTerimaRp = new javax.swing.JTextField();
        txtPeriode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceipt = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 177, Short.MAX_VALUE)
                    .addComponent(btnTambah)
                    .addGap(5, 5, 5)
                    .addComponent(btnBatal)
                    .addGap(5, 5, 5)
                    .addComponent(btnSimpan)
                    .addGap(5, 5, 5)
                    .addComponent(btnKeluar)
                    .addGap(0, 177, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKeluar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTambah)
                                .addComponent(btnBatal)
                                .addComponent(btnSimpan))))
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Nota");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Nama");

        btnCariPerson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCariPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kacapembesar.png"))); // NOI18N
        btnCariPerson.setText("Cari");
        btnCariPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPersonActionPerformed(evt);
            }
        });

        txtJenisMutasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Jenis Mutasi");

        btnCariJenisMutasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCariJenisMutasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kacapembesar.png"))); // NOI18N
        btnCariJenisMutasi.setText("Cari");
        btnCariJenisMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariJenisMutasiActionPerformed(evt);
            }
        });

        jLabel4.setText("Keterangan");

        jLabel6.setText("Terima Rp");

        jLabel7.setText("Periode Lap");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariPerson)
                                .addGap(18, 18, 18)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTerimaRp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(478, 478, 478))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariJenisMutasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJenisMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(738, 738, 738))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJenisMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnCariJenisMutasi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnCariPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerimaRp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCariPerson, jLabel1, jLabel2, jLabel3, txtJenisMutasi, txtKeterangan, txtNama, txtNota, txtPeriode, txtTanggal, txtTerimaRp});

        jScrollPane1.setToolTipText("Bila koreksi baris sebelumnya. Quantity dulu entry baru subtotal!");

        tblReceipt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   private void defaultButton() {
        btnTambah.setEnabled(true);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnKeluar.setEnabled(true);
    }

    private void editButton() {
        btnTambah.setEnabled(false);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnKeluar.setEnabled(true);
    }

    private void selectButton() {
        btnTambah.setEnabled(false);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKeluar.setEnabled(true);

    }

    private void enableForm(Boolean status) {
        autoNota();
        txtNota.setText(notajadi);
    }
    
    private void clearForm() {
        mutasi = null;
        txtTanggal.setText("");
        tblReceipt.clearSelection();
    }


private Nota findKodeNotaPolaTahunNomorDiAkhir(String jenisTransaksi)  {
    nota = new Nota();
    nota = Main.getAppService().findNotaAkhir(jenisTransaksi);
    if(nota == null){
       return null;
    }
    String polaTgl=nota.getPolaTgl();
    String thnIni = new SimpleDateFormat("yy").format(new Date());

    if(polaTgl == null || polaTgl.isEmpty()) {
    //isi metod nya
        String kodejadiawal=nota.getKodeTetap()+thnIni+"00001";
        nota.setId(nota.getId());
        nota.setLastnumber(1);
        nota.setNotajadi(kodejadiawal);
        nota.setPolaTgl(thnIni);
        return nota;
    } else {  
        int id = nota.getId();

          String pola = nota.getKodeTetap();
          String thnDB = polaTgl;

                int panjangnol= nota.getBanyakDigit()-String.valueOf(nota.getLastnumber()+1).length();
                int i=0;
                String pjgnol="";
                for (i=0;i<panjangnol;i++){
                    pjgnol=pjgnol+"0";
                     }
          int nomorAkhir = nota.getLastnumber()+1;
          String kodeNot = pola+thnDB+pjgnol+String.valueOf(nomorAkhir);

//        nota = new Nota();  //kalo nota sudah ada jangan di new  
           nota.setId(id);   
                nota.setNotajadi(kodeNot);
                nota.setLastnumber(nomorAkhir);
                nota.setPolaTgl(polaTgl);
       return nota;
    }
}        
    
private void autoNota() {
    if(!txtJenisMutasi.getText().isEmpty()) {
      notajadi  = new String();
    }
    if(findKodeNotaPolaTahunNomorDiAkhir(PANEL_NAME) == null){
          notajadi = null;    
          JOptionPane.showMessageDialog(this, "Master Kode Dokumen untuk PENERIMAAN Belum Dibuat!",
               "Kesalahan",JOptionPane.ERROR_MESSAGE);
       Main.getMainFrame().getMainTabPane().remove(this);
       panelReceipt = null;
  
    } else {
       notajadi  = findKodeNotaPolaTahunNomorDiAkhir(PANEL_NAME).getNotajadi();
    }
    
}    
    
private boolean validasiForm() {
     if(txtJenisMutasi.getText().isEmpty()){
   
        JOptionPane.showMessageDialog(this, "Jenis Mutasi Belum Ada!",
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}

private void loadFormToModel() throws ParseException {
          BigDecimal terima = new BigDecimal(txtTerimaRp.getText());
          Date date = new SimpleDateFormat("dd-MM-yyyy").parse(txtTanggal.getText());
          DateTime dateTransaksi = new DateTime(date); //transaksi kan tanggal sekarang
 
//          String bln="";
//          String thn="";
         
          //for normal period
          int per=dateTransaksi.getMonthOfYear();        
//          thn = String.valueOf(dateTransaksi.getYear());
//                  if(per<10){
//                     bln = "0"+String.valueOf(per);
//                  } else {
//                     bln = String.valueOf(per);
//                  }
          period = new String();
          period = txtPeriode.getText();
          
          if(person!=null){
          
//             person.setPembayaranTahunIni(person.getPembayaranTahunIni().add(terima));
             DateTime datetimePerson = new DateTime(person.getTanggalKomitmen());
             int selisihBulan = per-datetimePerson.getMonthOfYear();
             int selisihTahun = dateTransaksi.getYear() - datetimePerson.getYear();
             BigDecimal delta = new BigDecimal(selisihBulan + (12*selisihTahun));
             
             //harus mempertimbangkan periode yg terlewati
             person.setHutangTahunIni(person.getHutangTahunIni().add(delta.multiply(person.getKomitmen()).subtract(terima)));
             person.setKomitmenTahunIni(delta.multiply(person.getKomitmen()).add(person.getKomitmen()));
             person.setTotalHutang(person.getTotalHutang().add(delta.multiply(person.getKomitmen()).subtract(terima)));
             person.setPembayaranTahunIni(person.getPembayaranTahunIni().add(terima));
             } 
          
                    
           mutasi = new Mutasi();
           mutasi.setKeterangan(txtKeterangan.getText());
           mutasi.setTerimaRp(terima);
           if(person!=null){
             mutasi.setPersonId(person);
           }
           mutasi.setJenisMutasiId(jenisMutasi);
           mutasi.setKeluarRp(BigDecimal.ZERO);
           mutasi.setPeriodeLapor(period);
           mutasi.setTanggal(date);
           mutasi.setNota(notajadi);
           
           jenisMutasi.setPeriode(period);
           jenisMutasi.setTerimaRp(jenisMutasi.getTerimaRp().add(terima));
}

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);
    tblReceipt.setEnabled(true);
}//GEN-LAST:event_btnTambahActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
   clearForm();
   selectButton();
}//GEN-LAST:event_btnBatalActionPerformed

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            saveAction();
        } catch (ParseException ex) {
//            Exceptions.printStackTrace(ex);
            log.error(ex);
        }
}//GEN-LAST:event_btnSimpanActionPerformed

private void saveAction() throws ParseException {
    if(validasiForm()){
         loadFormToModel();    
        try{
        Main.getAppService().saveReceipt(person, jenisMutasi, mutasi, nota);
     
        //nyang penting code u save tak diinterupt dgn parameter lain2, mk transaction bisa jalan 
        JOptionPane.showMessageDialog(this, "Input Receipt Sudah Diposting!",
                "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException ex) { 
//            ex.printStackTrace(); 
            log.error(ex);
            JOptionPane.showMessageDialog(this, "INPUT RECEIPT GAGAL DIPOSTING!",
                "INFORMASI", JOptionPane.ERROR_MESSAGE);
        }
        defaultButton();
        clearForm();
        enableForm(false);
        
    }
}

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    Main.getMainFrame().getMainTabPane().remove(this);  //diremove dulu yg aktif
    panelReceipt = null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCariJenisMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariJenisMutasiActionPerformed
        // TODO add your handling code here:
        JenisMutasi jm = new LookUpJenisMutasi(null, true).getJenisMutasi();
        jenisMutasi = jm;
        txtJenisMutasi.setText(jm.getNamaMutasi());
        
        Date date;
        try {
          date = new SimpleDateFormat("dd-MM-yyyy").parse(txtTanggal.getText());
          DateTime dateTransaksi = new DateTime(date); //transaksi kan tanggal sekarang
          String bln="";
          String thn="";
         
          //for normal period
          int per=dateTransaksi.getMonthOfYear();        
          thn = String.valueOf(dateTransaksi.getYear());
                  if(per<10){
                     bln = "0"+String.valueOf(per);
                  } else {
                     bln = String.valueOf(per);
                  }
           txtPeriode.setText(thn+bln);
         } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);          
    }
    }//GEN-LAST:event_btnCariJenisMutasiActionPerformed

    private void btnCariPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPersonActionPerformed
        // TODO add your handling code here:
        Person p = new LookUpPerson(null, true).getPerson();
        try {

            //menangkap value dari lookup
            if(p !=null) {
                person = p;
                txtNama.setText(p.getNama());
                listPerson = Main.getAppService().findPersonListNama(p.getNama());
                refreshTable();
            }
        } catch (Exception e){
            log.error(e);
        }
    }//GEN-LAST:event_btnCariPersonActionPerformed




public class TabelModelReceipt extends AbstractTableModel{
    private final List<Person> listPersons;
    private final String[] HEADER = new String[] {"PERSON_ID","N A M A", "STATUS", 
        "KOMITMEN","PEMBAYARANTAHUNINI"};
    
    

    public TabelModelReceipt(List<Person> listPerson) {
        this.listPersons = listPerson;
    }

    @Override
    public int getRowCount() {
        return listPersons.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      Person md = listPersons.get(rowIndex);
      switch(columnIndex){
          case 0:
              return md.getPersonId();
          case 1:
              return md.getNama();
          case 2:
              return md.getStatus();
          case 3:
              return md.getKomitmen();
         case 4:
              return md.getPembayaranTahunIni();              
          default:
              return "";
      }
    }
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        switch(columnIndex) {
            case 1:
                return int.class;
            case 3: 
            case 4:    
                return BigDecimal.class;
            default: return String.class;
        }
    }
    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
          return false;
    }
    
    @Override
    public void setValueAt(Object value, int rowIndex, int columnIndex) {
//    Person md = listPersons.get(rowIndex);
//    
//    if(columnIndex == 2 ){
//
//        md.setTerimaRp((BigDecimal) value);
//        fireTableDataChanged();
//        }
//    
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariJenisMutasi;
    private javax.swing.JButton btnCariPerson;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReceipt;
    private javax.swing.JTextField txtJenisMutasi;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPeriode;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTerimaRp;
    // End of variables declaration//GEN-END:variables
}
