
/*
 * PanelPengeluaran.java
 *
 * Created on Sep 08, 2016, 2:19:36 PM
 */
package mfauz.desktop.panel.transaksi;

import com.artitraining.mfauz.model.JenisMutasi;
import com.artitraining.mfauz.model.Mutasi;
import com.artitraining.mfauz.model.Nota;
import com.artitraining.mfauz.model.Person;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.panel.lookup.LookUpJenisMutasi;
//import mfauz.desktop.util.NomorNota;
import mfauz.desktop.util.TextComponentUtils;
import org.apache.log4j.Logger;
import org.joda.time.DateTime;
import org.openide.util.Exceptions;

public class PanelPengeluaranR extends javax.swing.JComponent {
    public static final String PANEL_NAME = "PENGELUARAN";
    private static PanelPengeluaranR panelReceipt;
    private List<Mutasi> listMutasiDetails=new ArrayList<Mutasi>();
    private Mutasi mutasi;
    private Person person;
    private JenisMutasi jenisMutasi;
    private String notajadi, period;
//    private NomorNota nomorNota;
    private Nota nota;
    private static final Logger log = Logger.getLogger(PanelPengeluaranR.class);

    /** Creates new form PanelPembelian */
    public PanelPengeluaranR() {
        initComponents();
        tblPayment.setAutoCreateColumnsFromModel(false);
        defaultButton();
        enableForm(false);
        txtTanggal.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
//        editButton();
    }
    
     public static PanelPengeluaranR getPanelPayment() {
        if (panelReceipt == null) {
            panelReceipt = new PanelPengeluaranR();
        }
        return panelReceipt;
    }
    
    private void refreshTable() {
         tblPayment.setModel(new TabelModelReceipt(listMutasiDetails));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTanggal = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJenisMutasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCariJenisMutasi = new javax.swing.JButton();
        txtKeterangan = new javax.swing.JTextField();
        txtKeluarRp = new javax.swing.JTextField();
        txtPeriode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 177, Short.MAX_VALUE)
                    .addComponent(btnTambah)
                    .addGap(5, 5, 5)
                    .addComponent(btnBatal)
                    .addGap(5, 5, 5)
                    .addComponent(btnSimpan)
                    .addGap(5, 5, 5)
                    .addComponent(btnKeluar)
                    .addGap(0, 177, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKeluar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTambah)
                                .addComponent(btnBatal)
                                .addComponent(btnSimpan))))
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Nota");

        jLabel2.setText("Tanggal");

        txtJenisMutasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Jenis Mutasi");

        btnCariJenisMutasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCariJenisMutasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kacapembesar.png"))); // NOI18N
        btnCariJenisMutasi.setText("Cari");
        btnCariJenisMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariJenisMutasiActionPerformed(evt);
            }
        });

        jLabel4.setText("Keterangan");

        jLabel6.setText("Pengeluaran Rp");

        jLabel7.setText("Periode Lap");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariJenisMutasi))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtTanggal))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKeluarRp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtJenisMutasi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnCariJenisMutasi))
                .addGap(13, 13, 13)
                .addComponent(txtJenisMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeluarRp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, txtJenisMutasi, txtKeluarRp, txtKeterangan, txtNota, txtPeriode, txtTanggal});

        jScrollPane1.setToolTipText("Bila koreksi baris sebelumnya. Quantity dulu entry baru subtotal!");

        tblPayment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPayment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   private void defaultButton() {
        btnTambah.setEnabled(true);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnKeluar.setEnabled(true);
    }

    private void editButton() {
        btnTambah.setEnabled(false);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnKeluar.setEnabled(true);
    }

    private void selectButton() {
        btnTambah.setEnabled(false);
        btnBatal.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKeluar.setEnabled(true);

    }

    private void enableForm(Boolean status) {
        autoNota();
        txtNota.setText(notajadi);
    }
    
    private void clearForm() {
        mutasi = null;
        txtTanggal.setText("");
        listMutasiDetails=new ArrayList<Mutasi>();
        tblPayment.setModel(new TabelModelReceipt(listMutasiDetails));
    }

private void autoNota() {
    if(!txtJenisMutasi.getText().isEmpty()) {
//      nomorNota= new NomorNota();
      notajadi  = new String();
    }
    if(findKodeNotaPolaTahunNomorDiAkhir(PANEL_NAME) == null){
          notajadi = null;    
          JOptionPane.showMessageDialog(this, "Master Kode Dokumen untuk PEMBAYARAN Belum Dibuat!",
               "Kesalahan",JOptionPane.ERROR_MESSAGE);
       Main.getMainFrame().getMainTabPane().remove(this);
       panelReceipt = null;
  
    } else {
       notajadi  = findKodeNotaPolaTahunNomorDiAkhir(PANEL_NAME).getNotajadi();
    }
    
}    
    
private boolean validasiForm() {
     if(txtJenisMutasi.getText().isEmpty()){
   
        JOptionPane.showMessageDialog(this, "Jenis Mutasi Belum Ada!",
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}

private Nota findKodeNotaPolaTahunNomorDiAkhir(String jenisTransaksi)  {
    nota = new Nota();
    nota = Main.getAppService().findNotaAkhir(jenisTransaksi);
    if(nota == null){
       return null;
    }
    String polaTgl=nota.getPolaTgl();
    String thnIni = new SimpleDateFormat("yy").format(new Date());

    if(polaTgl == null || polaTgl.isEmpty()) {
    //isi metod nya
        String kodejadiawal=nota.getKodeTetap()+thnIni+"00001";
        nota.setId(nota.getId());
        nota.setLastnumber(1);
        nota.setNotajadi(kodejadiawal);
        nota.setPolaTgl(thnIni);
        return nota;
    } else {  
        int id = nota.getId();

          String pola = nota.getKodeTetap();
          String thnDB = polaTgl;

                int panjangnol= nota.getBanyakDigit()-String.valueOf(nota.getLastnumber()+1).length();
                int i=0;
                String pjgnol="";
                for (i=0;i<panjangnol;i++){
                    pjgnol=pjgnol+"0";
                     }
          int nomorAkhir = nota.getLastnumber()+1;
          String kodeNot = pola+thnDB+pjgnol+String.valueOf(nomorAkhir);

//        nota = new Nota();  
           nota.setId(id);   
                nota.setNotajadi(kodeNot);
                nota.setLastnumber(nomorAkhir);
                nota.setPolaTgl(polaTgl);
       return nota;
    }
}        

private void loadFormToModel() throws ParseException {
          BigDecimal terima = new BigDecimal(txtKeluarRp.getText());
          Date date = new SimpleDateFormat("dd-MM-yyyy").parse(txtTanggal.getText());
//          DateTime dateTransaksi = new DateTime(date); //transaksi kan tanggal sekarang
 
//          String bln="";
//          String thn="";
         
          //for normal period
//          int per=dateTransaksi.getMonthOfYear();        
//          thn = String.valueOf(dateTransaksi.getYear());
//                  if(per<10){
//                     bln = "0"+String.valueOf(per);
//                  } else {
//                     bln = String.valueOf(per);
//                  }
          
           period = new String();
           period = txtPeriode.getText();
                    
           mutasi = new Mutasi();
           mutasi.setKeterangan(txtKeterangan.getText());
           mutasi.setTerimaRp(terima);
           if(person!=null){
             mutasi.setPersonId(person);
           }
           mutasi.setJenisMutasiId(jenisMutasi);
           mutasi.setKeluarRp(BigDecimal.ZERO);
           mutasi.setPeriodeLapor(period);
           mutasi.setTanggal(date);
           mutasi.setNota(notajadi);
           
           jenisMutasi.setPeriode(period);
           jenisMutasi.setTerimaRp(jenisMutasi.getTerimaRp().add(terima));
}

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);
    tblPayment.setEnabled(true);
}//GEN-LAST:event_btnTambahActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
   try{
        //perhatikan object (listBeliDetail) dan paramaternya baik2
   listMutasiDetails.remove(tblPayment.getSelectedRow());  
       //getselectedrow tak dikurangi 1 krn sudah ada judul yg nempati 0
       //refresh berfungsi me refresh tabel dan total setelah dihapus satu baris
   refreshTable();
   } catch (ArrayIndexOutOfBoundsException arrayx){
       JOptionPane.showMessageDialog(this, "PILIH Yang Akan DIHAPUS!",
               "ERROR",JOptionPane.ERROR_MESSAGE);
   
   }
}//GEN-LAST:event_btnBatalActionPerformed

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            saveAction();
        } catch (ParseException ex) {
//            Exceptions.printStackTrace(ex);
            log.error(ex);
        }
}//GEN-LAST:event_btnSimpanActionPerformed

private void saveAction() throws ParseException {
    if(validasiForm()){
         loadFormToModel();    
        try{
   
        Main.getAppService().savePayment(jenisMutasi, mutasi, nota);
        //nyang penting code u save tak diinterupt dgn parameter lain2, mk transaction bisa jalan 
        JOptionPane.showMessageDialog(this, "Input Payment Sudah Diposting!",
                "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) { 
//            ex.printStackTrace(); 
            log.error(ex);
            JOptionPane.showMessageDialog(this, "INPUT PAYMENT GAGAL DIPOSTING!",
                "INFORMASI", JOptionPane.ERROR_MESSAGE);
        }
        defaultButton();
        clearForm();
        enableForm(false);
        
    }
}

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    Main.getMainFrame().getMainTabPane().remove(this);  //diremove dulu yg aktif
    panelReceipt = null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCariJenisMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariJenisMutasiActionPerformed
        // TODO add your handling code here:
        JenisMutasi jm = new LookUpJenisMutasi(null, true).getJenisMutasi();
        jenisMutasi = jm;
      
        Date date;
        try {
          date = new SimpleDateFormat("dd-MM-yyyy").parse(txtTanggal.getText());
          DateTime dateTransaksi = new DateTime(date); //transaksi kan tanggal sekarang
          String bln="";
          String thn="";
         
          //for normal period
          int per=dateTransaksi.getMonthOfYear();        
          thn = String.valueOf(dateTransaksi.getYear());
                  if(per<10){
                     bln = "0"+String.valueOf(per);
                  } else {
                     bln = String.valueOf(per);
                  }
           txtPeriode.setText(thn+bln);
         } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);          
    }       
    }//GEN-LAST:event_btnCariJenisMutasiActionPerformed




public class TabelModelReceipt extends AbstractTableModel{
    private final List<Mutasi> listMutasiDetail;
    private final String[] HEADER = new String[] {"PERSON_ID","KETERANGAN", "PENERIMAAN_RP", 
        "PERIOD_LAP"};
    
    

    public TabelModelReceipt(List<Mutasi> listMutasiDetil) {
        this.listMutasiDetail = listMutasiDetil;
    }

    @Override
    public int getRowCount() {
        return listMutasiDetail.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      Mutasi md = listMutasiDetail.get(rowIndex);
      switch(columnIndex){
          case 0:
              return md.getPersonId().getPersonId();
          case 1:
              return md.getKeterangan();
          case 2:
              return TextComponentUtils.formatNumber(md.getTerimaRp());
          case 3:
              return md.getPeriodeLapor();
          default:
              return "";
      }
    }
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        switch(columnIndex) {
            case 2: 
                return BigDecimal.class;
            default: return String.class;
        }
    }
    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return columnIndex == 1||columnIndex == 2|| columnIndex==4;
    }
    
    @Override
    public void setValueAt(Object value, int rowIndex, int columnIndex) {
    Mutasi md = listMutasiDetail.get(rowIndex);
    
    if(columnIndex == 2 ){

        md.setTerimaRp((BigDecimal) value);
        fireTableDataChanged();
        }
    
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariJenisMutasi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtJenisMutasi;
    private javax.swing.JTextField txtKeluarRp;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPeriode;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
