
/*
 * PanelJenisMutasi.java
 *
 * Created on Sep 8, 2016, 11:45:46 AM
 */
package mfauz.desktop.panel.master;

import com.artitraining.mfauz.model.JenisMutasi;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.util.TableUtil;
import mfauz.desktop.util.TextComponentUtils;
import org.apache.log4j.Logger;

/**
 *
 * @author ASUS
 */
public class PanelJenisMutasi extends javax.swing.JComponent 
    implements ListSelectionListener {
    private JenisMutasi jm;
    private List<JenisMutasi> listJenisMutasi = new ArrayList<JenisMutasi>();
    public static final String PANEL_NAME = "Jenis Mutasi";
    private static PanelJenisMutasi panelJenisMutasi;
//    private final Logger log = Logger.getLogger(panelJenisMutasi.getClass());
    
    /** Creates new form PanelJM */
    public PanelJenisMutasi() {
        initComponents();
        defaultButton();
        clearForm();
        enableForm(false);   
        TextComponentUtils.setAutoUpperCaseText(6, txtPeriode);
        TextComponentUtils.setAutoUpperCaseText(30, txtJenisMutasi);
    }

    public static PanelJenisMutasi getPanelJenisMutasi() {
        if(panelJenisMutasi==null) {
           panelJenisMutasi = new PanelJenisMutasi();
        }
        return panelJenisMutasi;
    }
    
    private void defaultButton() {
    btnTambah.setEnabled(true);
    btnEdit.setEnabled(false);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}
    
private void editButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(false);
    btnSimpan.setEnabled(true); 
    btnKeluar.setEnabled(true);
 
}

private void selectButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(true);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}

private void enableForm(Boolean status) {
    txtPeriode.setEnabled(status);
    txtJenisMutasi.setEnabled(status);
}

    private void clearForm(){
        txtPeriode.setText("");
        txtJenisMutasi.setText("");
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPeriode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtJenisMutasi = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnTambah.setMargin(new java.awt.Insets(5, 14, 2, 14));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnKeluar)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtCari.setEditable(false);

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "JenisMutasi", "Periode", "TerimaRp", "KeluarRp"
            }
        ));
        tblPerson.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblPerson);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Periode");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Jenis Mutasi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(txtJenisMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJenisMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel4, txtJenisMutasi, txtPeriode});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);

}//GEN-LAST:event_btnTambahActionPerformed

   private void loadModelToForm() {
      
        txtPeriode.setText(jm.getPeriode());
        txtJenisMutasi.setText(jm.getNamaMutasi());
    }
        
     private void updateTablePerson() {
        listJenisMutasi = Main.getAppService().findAllJenisMutasi();
        if(listJenisMutasi != null){
        tblPerson.setModel(new JenisMutasiTableModel(listJenisMutasi));
        tblPerson.setAutoCreateColumnsFromModel(true);
        tblPerson.getSelectionModel().addListSelectionListener(this);  
        TableUtil.autoResizeColumn(tblPerson);
        }
    }     

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
   if (jm!=null) {
       loadModelToForm();
       enableForm(Boolean.TRUE);
       editButton();
    }
}//GEN-LAST:event_btnEditActionPerformed


private void loadFormToModel(){
//      jm = new JenisMutasi();
      
      jm.setNamaMutasi(txtJenisMutasi.getText());
      jm.setPeriode(txtPeriode.getText());
      jm.setTerimaRp(BigDecimal.ZERO);
      jm.setKeluarRp(BigDecimal.ZERO);
}

private void simpanAction() {
    
    if(validateForm()){
        if (jm==null) {
            jm=new JenisMutasi();
        }
        loadFormToModel();  
        try {
        Main.getAppService().saveJenisMutasi(jm);
        }
        catch (Exception ex) {
//             ex.printStackTrace();
//             log.error(ex);
          JOptionPane.showMessageDialog(this, "Data gagal disimpan!"
            ,"Error",JOptionPane.ERROR_MESSAGE);
        }
        defaultButton();
        clearForm();
        enableForm(false);
        updateTablePerson();
        JOptionPane.showMessageDialog(this, "Data JenisMutasi Telah Disimpan!",
                "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }
}

private Boolean validateForm(){
    if(txtJenisMutasi.getText().equals("")) {
        JOptionPane.showMessageDialog(this, 
                "Harap isi field!", "Kesalahan",
                JOptionPane.ERROR_MESSAGE);
        return false;       
    }

   return true;
}

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanAction();
}//GEN-LAST:event_btnSimpanActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    Main.getMainFrame().getMainTabPane().remove(this);  //diremove dulu yg aktif
    panelJenisMutasi=null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    clearForm();
    defaultButton();
    enableForm(false);
}//GEN-LAST:event_btnBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJenisMutasi;
    private javax.swing.JTextField txtPeriode;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
          if(e.getValueIsAdjusting()) {
                return;
              }
        if(tblPerson.getSelectedRow() >=0) {
            jm = listJenisMutasi.get(tblPerson.getSelectedRow());
            loadModelToForm();
            enableForm(false);
            selectButton();
        }
    }

    public class JenisMutasiTableModel extends AbstractTableModel{
    private final List<JenisMutasi> listJenisMutasi;
    private final String[] HEADER = new String[] {"KODE", "JENIS MUTASI", "PERIODE", "TERIMA RP","KELUAR RP"};
   
    public JenisMutasiTableModel(List<JenisMutasi> listJenisMut) {
        this.listJenisMutasi = listJenisMut;
    }
    
    
    @Override
    public int getRowCount() {
        return listJenisMutasi.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      JenisMutasi j = listJenisMutasi.get(rowIndex);
      switch(columnIndex){
          
          case 0:
              return j.getId();
          case 1:
              return j.getNamaMutasi();
          case 2:
              return j.getPeriode();
          case 3:
              return TextComponentUtils.formatNumber(j.getTerimaRp());   
          case 4:
              return TextComponentUtils.formatNumber(j.getKeluarRp());
          default:
              return "";
      }
    }
    
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
         return String.class;
    }
    }    
    
}
