
/*
 * PanelMenu.java
 *
 * Created by Sarip on Mar 08, 2014, 16:14:32 
 */
package mfauz.desktop.panel.master;

import com.artitraining.mfauz.model.Menu;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.frame.MainFrame;
import mfauz.desktop.panel.lookup.LookUpMenu;
import mfauz.desktop.util.TableUtil;

/**
 *
 * @author Sarip
 */
//public class PanelMenu extends javax.swing.JComponent 
public class PanelMenu extends javax.swing.JInternalFrame
    implements ListSelectionListener {
    public static final String PANEL_NAME = "Master MENU";
    private static PanelMenu panelMenu;
    private Menu menu;
    private List<Menu> listMenu;
    
    /** Creates new form Panel */
    public PanelMenu() {
        initComponents();
        defaultButton();
        clearForm();
        enableForm(false);   
        updateMenu();
//          TextComponentUtils.setAutoUpperCaseText(30, txtNamaMenu);
    }
    
    public static PanelMenu getPanelMenu() {
        if(panelMenu==null) {
            panelMenu = new PanelMenu();
        }
        return panelMenu;
    }
    
    private void defaultButton() {
    btnTambah.setEnabled(true);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}
    
private void editButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
    btnSimpan.setEnabled(true); 
    btnKeluar.setEnabled(true);
 
}

private void selectButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(true);
    btnDelete.setEnabled(true);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}

private void enableForm(Boolean status) {
    txtNamaMenu.setEnabled(status);
    txtMenuLevel.setEnabled(status);
    txtPanelClass.setEnabled(status);
    txtUrutan.setEnabled(status);
    txtIdParent.setEnabled(status);
}

    private void clearForm(){
        txtNamaMenu.setText("");
        txtMenuLevel.setText("");
        txtPanelClass.setText("");
        txtUrutan.setText("");
        txtIdParent.setText("");
    }

   private void loadModelToForm() {
        txtNamaMenu.setText(menu.getId());       
        txtMenuLevel.setText(String.valueOf(menu.getMenuLevel()));
        txtPanelClass.setText(menu.getPanelClass());
        txtUrutan.setText(menu.getUrutan().toString());
        if(menu.getParent() == null) {
            txtIdParent.setText("");
        }  else {
           txtIdParent.setText(menu.getParent().getId());}
    }
        
     private void updateMenu() {
        listMenu = Main.getAppService().findAllMenu();
        tblMenu.setModel(new MenuTableModel(listMenu));
        tblMenu.setAutoCreateColumnsFromModel(true);
        tblMenu.getSelectionModel().addListSelectionListener(this);  
        TableUtil.autoResizeColumn(tblMenu);
    }     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMenuLevel = new javax.swing.JTextField();
        btnPilihIdParent = new javax.swing.JButton();
        txtUrutan = new javax.swing.JTextField();
        txtNamaMenu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPanelClass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdParent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnTambah.setMargin(new java.awt.Insets(5, 14, 2, 14));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kurang_1.png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnDelete, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnKeluar)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnDelete, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Menu", "Level", "PanelClass", "Urutan", "Id Parent"
            }
        ));
        tblMenu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("ID Parent");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Nama Menu");

        txtMenuLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuLevelActionPerformed(evt);
            }
        });

        btnPilihIdParent.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnPilihIdParent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kacapembesar.png"))); // NOI18N
        btnPilihIdParent.setText("Pilih ID Parent");
        btnPilihIdParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihIdParentActionPerformed(evt);
            }
        });

        txtUrutan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrutanActionPerformed(evt);
            }
        });

        txtNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMenuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Menu Level");

        txtPanelClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPanelClassActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Urutan");

        txtIdParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdParentActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Panel Class");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdParent, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPanelClass)
                                .addComponent(txtMenuLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNamaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(btnPilihIdParent, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUrutan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPanelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrutan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdParent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addComponent(btnPilihIdParent)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, txtMenuLevel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);
    txtNamaMenu.requestFocusInWindow();
}//GEN-LAST:event_btnTambahActionPerformed

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
 
    if (menu!=null) {
        listMenu=Main.getAppService().findAllMenu();
            loadModelToForm();
            txtNamaMenu.setEnabled(true);
            txtMenuLevel.setEnabled(true);
            txtPanelClass.setEnabled(true);
            txtIdParent.setEnabled(true);
            txtUrutan.setEnabled(true);
            
            editButton(); 
            //harus klik button simpan. kalo tidak: tak ada jeda tuk input editan
    } else {
             menu=null;
             clearForm();
             updateMenu();       
             return;
    }

}//GEN-LAST:event_btnEditActionPerformed

private void simpanAction() {
    
    if(validateForm()){
     try {       
        if (menu==null) {
            menu=new Menu();}
            loadFormToModel();    
            Main.getAppService().saveMenu(menu);    
            
        } catch (Exception ex) {
             ex.printStackTrace();
             JOptionPane.showMessageDialog(this, "Data Menu Gagal Disimpan! "+
             "\nMenu telah ada di DataBase = "+menu.getId()
            ,"Error",JOptionPane.ERROR_MESSAGE);
             clearForm();
             enableForm(false);
             return;
            }
        defaultButton();
        clearForm();
        enableForm(false);
        updateMenu();
        JOptionPane.showMessageDialog(this, "Data MENU TELAH DISIMPAN!",
                "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }
    menu=null;   //agar setelah save pd mode edit, action simpan siap dr null. kalotidak, dia akan mengedit
    updateMenu();
}


private Boolean validateForm(){
    if( txtMenuLevel.getText().equals("")  
            || txtNamaMenu.getText().equals("")
            || txtUrutan.getText().equals("")
           ) {
        JOptionPane.showMessageDialog(this, 
                "Harap isi semua field!!!", "Kesalahan",
                JOptionPane.ERROR_MESSAGE);
        return false;       
    }

   return true;
}

private void loadFormToModelEdit(){
//    if(menu!=null){
//    }
//    Main.getAppService().saveMenu(menu);
    }
    

private void loadFormToModel(){
   
       menu.setId(txtNamaMenu.getText());
       menu.setMenuLevel(Integer.parseInt(txtMenuLevel.getText()));
       menu.setPanelClass(txtPanelClass.getText());
       Menu menuParent=new Menu();
       menuParent.setId(txtIdParent.getText());
       menu.setParent(menuParent);
       menu.setUrutan(Integer.parseInt(txtUrutan.getText()));
       menu.setLastUpdate(new Date());
//       Pengguna p= new Pengguna();
//cek ke cara loginProcess
}

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanAction();
        updateMenu();
}//GEN-LAST:event_btnSimpanActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    if(menu!=null) {
            int message=JOptionPane.showConfirmDialog(this,"YAKIN AKAN MENGHAPUS MENU MASTER???",
                "KONFIRMASI ",JOptionPane.YES_NO_OPTION);
            if(message==0) {          
                Main.getAppService().deleteMenu(menu);
                defaultButton();
                clearForm();
                enableForm(false);
                menu = null;
                updateMenu();
                }
        } else {
        JOptionPane.showMessageDialog(this,
                "Tidak ada data yang dipilih!",
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnDeleteActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    MainFrame.getInstance().remove(this);  //diremove dulu yg aktif
    panelMenu=null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    clearForm();
    defaultButton();
    enableForm(false);
    menu = null; //SPY MENGEMBALIKAN NILAI NULL, SAAT BATAL
    updateMenu();
}//GEN-LAST:event_btnBatalActionPerformed

private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
}//GEN-LAST:event_txtCariActionPerformed



private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
    if(evt.getKeyChar()==KeyEvent.VK_ENTER) {
        listMenu = Main.getAppService()
                .findAllMenu();
                //nggak boleh query lagi <yang pake List>
                tblMenu.setModel(new MenuTableModel(listMenu)); //ini yg menampilkan dari DB ke panel
                tblMenu.setAutoCreateColumnsFromModel(true);
                tblMenu.getSelectionModel().addListSelectionListener(this);    
                TableUtil.autoResizeColumn(tblMenu);
    }
}//GEN-LAST:event_txtCariKeyPressed

private void txtMenuLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuLevelActionPerformed

}//GEN-LAST:event_txtMenuLevelActionPerformed

    private void btnPilihIdParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihIdParentActionPerformed
        // TODO add your handling code here:
          Menu m = new LookUpMenu(null, true).getMenu();
            try {   

            //menangkap value dari lookup
               if(m !=null) { 
                   txtIdParent.setText(m.getId());
                  }
              } catch (Exception e){
              } 
                txtIdParent.requestFocusInWindow();
    }//GEN-LAST:event_btnPilihIdParentActionPerformed

    private void txtUrutanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrutanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrutanActionPerformed

    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtPanelClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPanelClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPanelClassActionPerformed

    private void txtIdParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdParentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPilihIdParent;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdParent;
    private javax.swing.JTextField txtMenuLevel;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtPanelClass;
    private javax.swing.JTextField txtUrutan;
    // End of variables declaration//GEN-END:variables

public class MenuTableModel extends AbstractTableModel{
    private List<Menu> listMenu;
    private String[] HEADER = new String[] {"NAMA MENU", "MENULEVEL","PANEL CLASS",
        "URUTAN", "ID PARENT"};
   
    public MenuTableModel(List<Menu> listMenu) {
        this.listMenu = listMenu;
    }
    
    
    @Override
    public int getRowCount() {
        return listMenu.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      Menu m = listMenu.get(rowIndex);
      switch(columnIndex){
          
          case 0:
              return m.getId();
          case 1:
              return m.getMenuLevel();
          case 2:
              return m.getPanelClass(); 
          case 3:
              return m.getUrutan();
          case 4:
              return m.getParent();
          default:
              return "";
      }
    }
    
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        switch(columnIndex) {
            case 1:
            case 3:    
                return Integer.class;
        }
        return String.class;
    }
    }    
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
          if(e.getValueIsAdjusting()) {
                return;
              }
        if(tblMenu.getSelectedRow() >=0) {
            menu = listMenu.get(tblMenu.getSelectedRow());
            loadModelToForm();
            enableForm(false);
            selectButton();
        }
    }
}
