
/*
 * PanelGL.java
 *
 * Created by Sarip on Mar 28, 2014, 10:55:32 AM
 */
package mfauz.desktop.panel.master;

import com.artitraining.mfauz.model.Nota;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.util.TableUtil;
import mfauz.desktop.util.TextComponentUtils;

/**
 *
 * @author Sarip
 */
public class PanelNotaDokumen extends javax.swing.JComponent 
    implements ListSelectionListener {
    public static final String PANEL_NAME = "Kode Dokumen";
    private static PanelNotaDokumen panelKodeDokumen;
    private Nota nota;
    private List<Nota> listNota;
    
    /** Creates new form PanelRayon */
    public PanelNotaDokumen() {
        initComponents();
        defaultButton();
        clearForm();
        enableForm(false);   
//        updateTable();
        TextComponentUtils.setNumericTextOnly(txtJumlahDigitNomor);
    }
    
    public static PanelNotaDokumen getPanelKodeDokumen() {
        if(panelKodeDokumen==null) {
            panelKodeDokumen = new PanelNotaDokumen();
        }
        return panelKodeDokumen;
    }
    
    private void defaultButton() {
    btnTambah.setEnabled(true);
    btnEdit.setEnabled(false);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}
    
private void editButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(false);
    btnSimpan.setEnabled(true); 
    btnKeluar.setEnabled(true);
 
}

private void selectButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(true);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}

private void enableForm(Boolean status) {
    txtKodeTetap.setEnabled(status);
    txtCounter.setEnabled(status);
    cboJenisDok.setEnabled(status);
    txtPolaTanggal.setEnabled(status);
    txtJumlahDigitNomor.setEnabled(status);
}

    private void clearForm(){
        txtKodeTetap.setText("");
        txtCounter.setText("");
        txtPolaTanggal.setText("");
        cboJenisDok.setSelectedIndex(-1);
        txtJumlahDigitNomor.setText("");
        txtKodeJadi.setText("");
    }

   private void loadModelToForm() {
        txtKodeTetap.setText(nota.getKodeTetap());
        txtCounter.setText(String.valueOf(nota.getLastnumber()));
        cboJenisDok.setSelectedItem(nota.getJenisTrans());
        txtPolaTanggal.setText(nota.getPolaTgl());
        if(nota.getBanyakDigit() != null) {
        txtJumlahDigitNomor.setText(String.valueOf(nota.getBanyakDigit()));}
    }
        
     private void updateTable() {
        listNota = Main.getAppService().findAllNota();
        if(listNota != null) {
        tblKodeDok.setModel(new KodeDokumenTableModel(listNota));
        tblKodeDok.setAutoCreateColumnsFromModel(true);
        tblKodeDok.getSelectionModel().addListSelectionListener(this);  
        TableUtil.autoResizeColumn(tblKodeDok);
        } else {
          JOptionPane.showMessageDialog(this, "Data KODE DOKUMEN Masih Kosong!",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKodeDok = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCounter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboJenisDok = new javax.swing.JComboBox();
        txtKodeTetap = new javax.swing.JTextField();
        txtPolaTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtJumlahDigitNomor = new javax.swing.JTextField();
        btnPosisiNomorDiAkhir = new javax.swing.JButton();
        btnPosisiNomorDiAwal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtKodeJadi = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnTambah.setMargin(new java.awt.Insets(5, 14, 2, 14));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnKeluar)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Nota Dokumen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        txtCari.setEditable(false);

        tblKodeDok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KodeTetap", "Jenis Dokumen", "Counter", "KodeTerakhir", "DigitNom"
            }
        ));
        tblKodeDok.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblKodeDok);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kode Tetap");

        txtCounter.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Counter Akhir");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Dokumen");

        cboJenisDok.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JENISMUTASI", "PENERIMAAN", "PENGELUARAN", " " }));
        cboJenisDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJenisDokActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pola Tanggal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Digit Nomer");

        btnPosisiNomorDiAkhir.setText("Nomor Di Akhir");
        btnPosisiNomorDiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosisiNomorDiAkhirActionPerformed(evt);
            }
        });

        btnPosisiNomorDiAwal.setText("Nomor Di Awal");
        btnPosisiNomorDiAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosisiNomorDiAwalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kode Jadi");

        txtKodeJadi.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnPosisiNomorDiAkhir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnPosisiNomorDiAwal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeJadi, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtCounter, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtJumlahDigitNomor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtPolaTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(cboJenisDok, javax.swing.GroupLayout.Alignment.TRAILING, 0, 289, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtKodeTetap, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKodeTetap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cboJenisDok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolaTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahDigitNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPosisiNomorDiAwal)
                    .addComponent(btnPosisiNomorDiAkhir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeJadi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboJenisDok, jLabel1, txtCounter, txtJumlahDigitNomor, txtKodeTetap, txtPolaTanggal});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);
    txtKodeTetap.requestFocusInWindow();
}//GEN-LAST:event_btnTambahActionPerformed

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
 
    if (nota!=null) {
            loadModelToForm();
            txtKodeTetap.setEnabled(true);
            cboJenisDok.setEnabled(true);
            txtCounter.setEnabled(true);
            txtJumlahDigitNomor.setEnabled(true);
            txtPolaTanggal.setEnabled(true);
            editButton(); 
            //harus klik button simpan. kalo tidak: tak ada jeda tuk input editan
        }

}//GEN-LAST:event_btnEditActionPerformed

private void simpanAction() {
    
    if(validateForm()){
     try {       
        if (nota==null) {
            nota=new Nota();
            loadFormToModel();    
            Main.getAppService().saveNota(nota);           
            }  else {
            loadFormToModel(); 
            Main.getAppService().saveNota(nota);    
           }
    
        } catch (Exception ex) {
             ex.printStackTrace();
             JOptionPane.showMessageDialog(this, "Data Gagal Disimpan! "
            ,"Error",JOptionPane.ERROR_MESSAGE);
             clearForm();
             enableForm(false);
             return;
            }
        defaultButton();
        clearForm();
        enableForm(false);
        updateTable();
        JOptionPane.showMessageDialog(this, "Data KODE DOKUMEN TELAH DISIMPAN!",
                "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }
    nota=null;   //agar setelah save pd mode edit, action simpan siap dr null. kalotidak, dia akan mengedit
    updateTable();
}

private Boolean validateForm(){
    if( txtKodeTetap.getText().equals("")
            || cboJenisDok.getSelectedIndex() == -1 
            || txtJumlahDigitNomor.getText().equals("")) {
                JOptionPane.showMessageDialog(this, 
                "Harap isi semua field!!!(Kode Tetap; Jenis Dokumen; Digit Nomer)", "Kesalahan",
                JOptionPane.ERROR_MESSAGE);
        return false;       
    }

   return true;
}


private void loadFormToModel(){
   nota.setKodeTetap(txtKodeTetap.getText());
   nota.setJenisTrans(String.valueOf(cboJenisDok.getSelectedItem()));
   if(txtCounter.getText() == null || txtCounter.getText().isEmpty()) {
   nota.setLastnumber(0);
   } else {
   nota.setLastnumber(Integer.parseInt(txtCounter.getText()));
   }
   nota.setPolaTgl(txtPolaTanggal.getText());
   nota.setBanyakDigit(Integer.parseInt(txtJumlahDigitNomor.getText()));
}

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanAction();
}//GEN-LAST:event_btnSimpanActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    Main.getMainFrame().getMainTabPane().remove(this);  //diremove dulu yg aktif
    panelKodeDokumen=null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    clearForm();
    defaultButton();
    enableForm(false);
    nota = null; //SPY MENGEMBALIKAN NILAI NULL, SAAT BATAL
    updateTable();
}//GEN-LAST:event_btnBatalActionPerformed



    private void btnPosisiNomorDiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosisiNomorDiAkhirActionPerformed
        // TODO add your handling code here:
        int jumlahDigit = Integer.parseInt(txtJumlahDigitNomor.getText());
        String digitNol="";
        for(int i=0;i<jumlahDigit;i++) {
            digitNol = digitNol +"0";
        }
        txtKodeJadi.setText(txtKodeTetap.getText()+txtPolaTanggal.getText()+digitNol);
    }//GEN-LAST:event_btnPosisiNomorDiAkhirActionPerformed

    private void btnPosisiNomorDiAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosisiNomorDiAwalActionPerformed
        // TODO add your handling code here:
        int jumlahDigit = Integer.parseInt(txtJumlahDigitNomor.getText());
        String digitNol="";
        for(int i=0;i<jumlahDigit;i++) {
            digitNol = digitNol +"0";
        }
        txtKodeJadi.setText(digitNol+txtKodeTetap.getText()+txtPolaTanggal.getText());
    }//GEN-LAST:event_btnPosisiNomorDiAwalActionPerformed

    private void cboJenisDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJenisDokActionPerformed
        // TODO add your handling code here:
        String tahun = new SimpleDateFormat("yyyy").format(new Date());
        String tahunbulan = new SimpleDateFormat("yyMM").format(new Date());
        if(cboJenisDok.getSelectedIndex() == -1){
           txtPolaTanggal.setText("");
        } else if(cboJenisDok.getSelectedIndex() == 4 ||
           cboJenisDok.getSelectedIndex() == 10 ||
           cboJenisDok.getSelectedIndex() == 11){
           txtPolaTanggal.setText(tahun);
        } else {
           txtPolaTanggal.setText(tahunbulan);
        }
        txtCounter.setText("0");
        txtJumlahDigitNomor.setText("5");
    }//GEN-LAST:event_cboJenisDokActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPosisiNomorDiAkhir;
    private javax.swing.JButton btnPosisiNomorDiAwal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cboJenisDok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKodeDok;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCounter;
    private javax.swing.JTextField txtJumlahDigitNomor;
    private javax.swing.JTextField txtKodeJadi;
    private javax.swing.JTextField txtKodeTetap;
    private javax.swing.JTextField txtPolaTanggal;
    // End of variables declaration//GEN-END:variables

public class KodeDokumenTableModel extends AbstractTableModel{
    private final List<Nota> listNota;
    private final String[] HEADER = new String[] {"KODE TETAP","JENIS DOKUMEN", "COUNTER", "KODE TERAKHIR", "DIGITNOM"};
   
    public KodeDokumenTableModel(List<Nota> listNota) {
        this.listNota = listNota;
    }
    
    
    @Override
    public int getRowCount() {
        return listNota.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      Nota n = listNota.get(rowIndex);
      switch(columnIndex){
          
          case 0:
               return n.getKodeTetap();
          case 1:
               return n.getJenisTrans();
          case 2:
               return n.getLastnumber();
          case 3:
               return n.getNotajadi();
          case 4:
              return n.getBanyakDigit();
          default:
              return "";
      }
    }
    
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        if(columnIndex ==4) {return Integer.class;} 
        return String.class;
    }
    }    
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
          if(e.getValueIsAdjusting()) {
                return;
              }
        if(tblKodeDok.getSelectedRow() >=0) {
            nota = listNota.get(tblKodeDok.getSelectedRow());
            loadModelToForm();
            selectButton();
        }
    }
}
