
/*
 * PanelPerson.java
 *
 * Created on Sep 3, 2012, 11:45:46 AM
 */
package mfauz.desktop.panel.master;

import com.artitraining.mfauz.model.Person;
import com.twmacinta.util.MD5;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import mfauz.desktop.Main;
import mfauz.desktop.util.TableUtil;
import mfauz.desktop.util.TextComponentUtils;

/**
 *
 * @author ASUS
 */
public class PanelPerson extends javax.swing.JComponent 
    implements ListSelectionListener {
    private Person person;
    private List<Person> listPerson;
    public static final String PANEL_NAME = "Master Person";
    private static PanelPerson panelMPerson;
    
    /** Creates new form PanelPerson */
    public PanelPerson() {
        initComponents();
           defaultButton();
        clearForm();
        enableForm(false);   
        
//        updateTablePerson();
          TextComponentUtils.setAutoUpperCaseText(45, txtKotaSektor);
          TextComponentUtils.setAutoUpperCaseText(30, txtNama);
          TextComponentUtils.formatNumber(txtKomitmen.getText());
    }

    public static PanelPerson getPanelPerson() {
        if(panelMPerson==null) {
            panelMPerson = new PanelPerson();
        }
        return panelMPerson;
    }
    
    private void defaultButton() {
    btnTambah.setEnabled(true);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}
    
private void editButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
    btnSimpan.setEnabled(true); 
    btnKeluar.setEnabled(true);
 
}

private void selectButton() {
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(true);
    btnDelete.setEnabled(true);
    btnSimpan.setEnabled(false); 
    btnKeluar.setEnabled(true);
 
}

private void enableForm(Boolean status) {
    txtKotaSektor.setEnabled(status);
    txtNama.setEnabled(status);
    txtKomitmen.setEnabled(status);
    tglKomitmen.setEnabled(status);
    cboStatus.setEnabled(status);
    tglPindah.setEnabled(status);
    pasAk.setEnabled(status);
}

    private void clearForm(){
        txtKomitmen.setText("");
        txtKotaSektor.setText("");
        txtNama.setText("");
        tglKomitmen.setDate(null);
        cboStatus.setSelectedIndex(-1);
        tglPindah.setDate(null);
        pasAk.setText("");
        person=null;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtKotaSektor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKomitmen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tglKomitmen = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox();
        tglPindah = new com.toedter.calendar.JDateChooser();
        pasAk = new javax.swing.JPasswordField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnTambah.setMargin(new java.awt.Insets(5, 14, 2, 14));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/disket kuning.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kurang_1.png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/panah kanan_2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfauz/desktop/image/kali_1.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnDelete, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnKeluar)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnDelete, btnEdit, btnKeluar, btnSimpan, btnTambah});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtCari.setEditable(false);

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Status", "TglKomit", "Komitmen"
            }
        ));
        tblPerson.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblPerson);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kota & Sektor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("N a m a ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tgl. Komitmen");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("KomitmenRp");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tgl. Pindah");

        tglKomitmen.setDateFormatString("dd-MM-yyyy");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Status");

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PELAJAR", "KARYAWAN" }));
        cboStatus.setToolTipText("");

        tglPindah.setDateFormatString("dd-MM-yyyy");

        pasAk.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKotaSektor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglKomitmen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKomitmen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglPindah, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasAk, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKotaSektor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglKomitmen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKomitmen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tglPindah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pasAk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboStatus, jLabel1, jLabel12, jLabel2, jLabel4, jLabel6, jLabel8, tglKomitmen, txtKomitmen, txtKotaSektor, txtNama});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    editButton();
    enableForm(true);
    autoNoKode();

    cboStatus.requestFocusInWindow();
}//GEN-LAST:event_btnTambahActionPerformed

   private void loadModelToForm() {
        txtKomitmen.setText(String.valueOf(person.getKomitmen()));
        txtKotaSektor.setText(person.getKotaSektor());
        txtNama.setText(person.getNama());
        tglKomitmen.setDate(person.getTanggalKomitmen());
        tglPindah.setDate(person.getTanggalPindah());
        cboStatus.setSelectedItem(person.getStatus());
        if(person.getPersonId()==0) {
            txtKomitmen.setText("");
        }
    }
        
     private void updateTablePerson() {
        listPerson = Main.getAppService().findAllPerson();
        if(listPerson != null){
        tblPerson.setModel(new PersonTableModel(listPerson));
        tblPerson.setAutoCreateColumnsFromModel(true);
        tblPerson.getSelectionModel().addListSelectionListener(this);  
        TableUtil.autoResizeColumn(tblPerson);
        }
    }     

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
   if (person!=null) {
       loadModelToForm();
       enableForm(Boolean.TRUE);
       editButton();
    }
}//GEN-LAST:event_btnEditActionPerformed

public void autoNoKode() {

}

private void loadFormToModel(){
//    person = new Person();
    person.setNama(txtNama.getText());
    person.setStatus(String.valueOf(cboStatus.getSelectedItem()));
    person.setKotaSektor(txtKotaSektor.getText());
    person.setKomitmen(new BigDecimal(txtKomitmen.getText()));
    person.setTanggalKomitmen(tglKomitmen.getDate());
    if(tglPindah.getDate() == null){
      person.setTanggalPindah(null);
    } else { 
      person.setTanggalPindah(tglPindah.getDate()); 
    }
    person.setHutangTahunIni(BigDecimal.ZERO);
    person.setHutangTahunLalu(BigDecimal.ZERO);
    person.setKomitmenTahunIni(new BigDecimal(txtKomitmen.getText()));
    person.setPembayaranTahunIni(BigDecimal.ZERO);
    person.setTotalHutang(BigDecimal.ZERO);
    String kataSandi = new MD5(new String(pasAk.getPassword())).asHex();
    person.setPassword(kataSandi);
}

private void simpanAction() {
    
    if(validateForm()){
        if (person==null) {
            person=new Person();
        }
        loadFormToModel();  
        try {
        Main.getAppService().savePerson(person);
        }
        catch (Exception ex) {
             ex.printStackTrace();
          JOptionPane.showMessageDialog(this, "Data gagal disimpan!"
            ,"Error",JOptionPane.ERROR_MESSAGE);
        }
        defaultButton();
        clearForm();
        enableForm(false);
        updateTablePerson();
        JOptionPane.showMessageDialog(this, "Data Person Telah Disimpan!",
                "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }
}

private Boolean validateForm(){
    if(txtNama.getText().equals("") || txtKomitmen.getText().equals("")
          || cboStatus.getSelectedIndex()== -1 || tglKomitmen.getDate() == null) {
        JOptionPane.showMessageDialog(this, 
                "Harap isi semua field Penting!!", "Kesalahan",
                JOptionPane.ERROR_MESSAGE);
        return false;       
    }

   return true;
}

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanAction();
}//GEN-LAST:event_btnSimpanActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    if(person!=null) {
          int message=JOptionPane.showConfirmDialog(this, "Yakin akan menghapus data person? ==> "
                +person.getPersonId()+" "+person.getNama(),
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION, 1);
           if(message==0){
            Main.getAppService().deletePerson(person);
            defaultButton();
            clearForm();
            enableForm(false);
            person = null;
            updateTablePerson();
            JOptionPane.showMessageDialog(this,
                    "Data Telah Terhapus!",
                    "Selesai", JOptionPane.INFORMATION_MESSAGE);
           } else {
                defaultButton();
                clearForm();
                enableForm(false);}
    } else {
        JOptionPane.showMessageDialog(this,
                "Tidak ada data yang dipilih!",
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnDeleteActionPerformed

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    Main.getMainFrame().getMainTabPane().remove(this);  //diremove dulu yg aktif
    panelMPerson=null;  //baru kemudian objek panelBarang dibikin null
}//GEN-LAST:event_btnKeluarActionPerformed

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    clearForm();
    defaultButton();
    enableForm(false);
}//GEN-LAST:event_btnBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pasAk;
    private javax.swing.JTable tblPerson;
    private com.toedter.calendar.JDateChooser tglKomitmen;
    private com.toedter.calendar.JDateChooser tglPindah;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKomitmen;
    private javax.swing.JTextField txtKotaSektor;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
          if(e.getValueIsAdjusting()) {
                return;
              }
        if(tblPerson.getSelectedRow() >=0) {
            person = listPerson.get(tblPerson.getSelectedRow());
            loadModelToForm();
            enableForm(false);
            selectButton();
        }
    }

    public class PersonTableModel extends AbstractTableModel{
    private final List<Person> listPerson;
    private final String[] HEADER = new String[] {"KODE", "NAMA", "STATUS", "TGL KOMIT","KOMIT RP"};
   
    public PersonTableModel(List<Person> listPerson) {
        this.listPerson = listPerson;
    }
    
    
    @Override
    public int getRowCount() {
        return listPerson.size();   // size untuk tipe List
    }

    @Override
    public int getColumnCount() {
        return HEADER.length;   //length untuk tipe array
    }
    
    @Override
    public String getColumnName(int column){
        return HEADER[column];
    }

    
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
      Person p = listPerson.get(rowIndex);
      switch(columnIndex){
          
          case 0:
              return p.getPersonId();
          case 1:
              return p.getNama();
          case 2:
              return p.getStatus();
          case 3:
              return p.getTanggalKomitmen();   
          case 4:
              return TextComponentUtils.formatNumber(p.getKomitmen());
          default:
              return "";
      }
    }
    
 
    @Override
    public Class<?> getColumnClass(int columnIndex) {
         return String.class;
    }
}    
    
}
